// This code was automatically generated by GenHeader.py
#pragma once
#include "JamUtil.h"

// Forward declare the asset array
extern JULoadedAsset ASSETS[1];

#ifdef ASSETS_IMPLEMENTATION
JULoadedAsset ASSETS[] = {
    {"assets/test.png"},
};
#endif

typedef struct Assets {
    JULoader loader;
    VK2DTexture textest;
} Assets;

// Functions to create and destroy the asset struct
Assets *buildAssets();
void destroyAssets(Assets *s);

#ifdef ASSETS_IMPLEMENTATION
Assets *buildAssets() {
    Assets *s = malloc(sizeof(struct Assets));
    s->loader = juLoaderCreate(ASSETS, 1);
    s->textest = juLoaderGetTexture(s->loader, "assets/test.png");
    return s;
}

void destroyAssets(Assets *s) {
    juLoaderFree(s->loader);
    free(s);
}
#endif
