// This code was automatically generated by GenHeader.py
#pragma once
#include "JamUtil.h"

// Forward declare the asset array
extern JULoadedAsset ASSETS[4];

#ifdef ASSETS_IMPLEMENTATION
JULoadedAsset ASSETS[] = {
    {"assets/Background.png"},
    {"assets/Foreground.png"},
    {"assets/Player.png"},
    {"assets/PlayerThruster.png"},
};
#endif

typedef struct Assets {
    JULoader loader;
    VK2DTexture texBackground;
    VK2DTexture texForeground;
    VK2DTexture texPlayer;
    VK2DTexture texPlayerThruster;
} Assets;

// Functions to create and destroy the asset struct
Assets *buildAssets();
void destroyAssets(Assets *s);

#ifdef ASSETS_IMPLEMENTATION
Assets *buildAssets() {
    Assets *s = malloc(sizeof(struct Assets));
    s->loader = juLoaderCreate(ASSETS, 4);
    s->texBackground = juLoaderGetTexture(s->loader, "assets/Background.png");
    s->texForeground = juLoaderGetTexture(s->loader, "assets/Foreground.png");
    s->texPlayer = juLoaderGetTexture(s->loader, "assets/Player.png");
    s->texPlayerThruster = juLoaderGetTexture(s->loader, "assets/PlayerThruster.png");
    return s;
}

void destroyAssets(Assets *s) {
    juLoaderFree(s->loader);
    free(s);
}
#endif
